config/routes.rb
Rails.application.routes.draw do
  root to: 'company/welcome#index'

  namespace :admin do
    resources :admins, :except => [:edit]
    resources :markers, :except => [:show]
    resources :characters, :except => [:show]
    resources :companies, :except => [:show]
    resources :staffs, :except => [:show]
    resources :apps, :except => [:show]
    resources :advertisings, :except => [:show]
    get '/' => 'welcome#index'
    get '/signin' => 'sessions#signin'
    post '/signin' => 'sessions#create'
    get '/signout' => 'sessions#signout'
  end

  namespace :company do
    resources :staffs do
      collection do
        get :sign_in
        post 'session_create'
        delete :sign_out
      end
    end
    resources :markers, except: [:show], shallow: true do
      resources :advertisings
    end
    get '/' => 'welcome#index'
  end

  namespace :api, { format: 'json' } do
    namespace :v1 do
      post '/signup' => 'users#signup'
      get '/apps/:id/resources' => 'apps#resources'
      get '/apps/:id/relations' => 'apps#relations'
      post '/apps/:id/impressions' => 'apps#impressions'
      post '/apps/:id/reaches' => 'apps#reaches'
    end
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/models/advertising.rb
class Advertising < ActiveRecord::Base
  belongs_to :marker
  has_many :impressions, :dependent => :destroy
  has_many :reaches, :dependent => :destroy

  mount_uploader :image, AdvertisingImageUploader


  validates :link, presence: true
  validates :image, presence: true
  validates :marker_id, presence: true

  scope :with_marker, -> (marker_id) { where(marker: marker_id) }
  scope :with_company, -> (company_id) { joins(marker: :company).merge(Company.where(id: company_id)) }

  def impressions_count
    impressions.count
  end

  def reaches_count
    reaches.count
  end
end

app/models/app.rb
class App < ActiveRecord::Base
  has_many :apps_companies, :dependent => :destroy
  has_many :companies, :through => :apps_companies

  validates :name, presence: true
end

app/models/apps_company.rb
class AppsCompany < ActiveRecord::Base
  belongs_to :app
  belongs_to :company
end

app/models/character.rb
class Character < ActiveRecord::Base
  has_many :companies, :dependent => :destroy

  mount_uploader :thumbnail, CharacterThumbnailUploader

  validates :name, presence: true
  validates :thumbnail, presence: true
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :apps_companies, :dependent => :destroy
  has_many :apps, :through => :apps_companies
  has_many :markers, :dependent => :destroy
  has_many :staffs, :dependent => :destroy
  belongs_to :character

  accepts_nested_attributes_for :apps_companies, :allow_destroy => true

  validates :name, presence: true
  validates :character_id, presence: true

  def impressions_count
    Impression.joins(advertising: {marker: :company}).merge(Company.where(id: id)).count
  end

  def reaches_count
    Reach.joins(advertising: {marker: :company}).merge(Company.where(id: id)).count
  end
end

app/models/impression.rb
class Impression < ActiveRecord::Base
  belongs_to :advertising
  belongs_to :user

  [:advertising_id, :user_id, :latitude, :longitude, :displayed_at, :app_id].each{|sym|
    validates sym, presence: true, on: :create
  }
  scope :with_advertising, -> (advertising_id) { where(advertising: advertising_id) }
end

app/models/marker.rb
class Marker < ActiveRecord::Base
  belongs_to :company
  has_many :advertisings, :dependent => :destroy

  mount_uploader :image, MarkerImageUploader
  before_destroy :validate_updated_at
  after_destroy :delete_from_vuforia


  validates :name, presence: true
  validates :company_id, presence: true
  validates :image, presence: true

  validate :validate_updated_at, on: :update

  scope :with_company, -> (company_id) { where(company: company_id) }

  def impressions_count
    Impression.joins(advertising: :marker).merge(Marker.where(id: id)).count
  end

  def reaches_count
    Reach.joins(advertising: :marker).merge(Marker.where(id: id)).count
  end

  def delete_from_vuforia
    Vuforia.delete target_id
  end

private
  def validate_updated_at
    if updated_at + 120 > Time.now
      errors.add(" ", "連続して変更することはできません。約120秒待って再度実行してください")
      return false
    end
  end
end

app/models/reach.rb
class Reach < ActiveRecord::Base
  belongs_to :advertising
  belongs_to :user

  [:advertising_id, :user_id, :latitude, :longitude, :displayed_at, :app_id].each{|sym|
    validates sym, presence: true, on: :create
  }
  scope :with_advertising, -> (advertising_id) { where(advertising: advertising_id) }
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  belongs_to :company

  validates :name, presence: true
  validates :company_id, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  has_secure_password

  scope :with_company, -> (company_id) { where(company: company_id) }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :impressions, :dependent => :destroy
  has_many :reaches, :dependent => :destroy
  after_initialize :set_default_value

  private
  def set_default_value
    self.uuid = SecureRandom.uuid
  end
end

app/models/vuforia.rb
class Vuforia
  class << self
    def upload(marker)
      begin
        path = marker.image.url
        size = FastImage.size(path)

        name = "marker"+marker.id.to_s
        #advertisings = marker.advertisings.where(enabled:true).pluck(:id)
        #meta = ({marker_id:marker.id, character_id: marker.company.character.id, advertisings:advertisings}).to_json
        meta = marker.id

        if marker.target_id
          connection.update_target(marker.target_id, name, path, size[0], if marker.enabled then 1 else 0 end, meta)
        else
          res = connection.add_target(name, path, size[0], if marker.enabled then 1 else 0 end, meta)
          marker.target_id = (JSON.parse res)["target_id"]
          marker.save!(validate: false)
        end
        true
      rescue => e
        false
      end
    end

    def delete(target_id)
      connection.delete_target target_id
    end

    def connection
      Vws::Api.new(Rails.application.config.vuforia_access_key, Rails.application.config.vuforia_secret_key)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_staff
    redirect_to sign_in_company_staffs_path unless session[:id]
  end

  def authenticate_admin
    redirect_to admin_signin_path unless session[:admin_id]
  end

  def current_staff
    if session[:id]
      Staff.find(session[:id])
    end
  end

  def current_admin
    if session[:admin_id]
      Admin.find(session[:admin_id])
    end
  end

  helper_method :current_staff
  helper_method :current_admin

end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/apps_helper.rb
module Admin::AppsHelper
end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/helpers/admin/markers_helper.rb
module Admin::MarkersHelper
end

app/helpers/admin/staffs_helper.rb
module Admin::StaffsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def shallow_args(namespace, parent, child)
    if namespace.nil?
      child.try(:new_record?) ? [parent, child] : child
    else
      child.try(:new_record?) ? [namespace, parent, child] : [namespace, child]
    end
  end
end

app/views/admin/_header.erb
<nav class="navbar navbar-default navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to admin_path, class: 'navbar-brand' do %>
          <%= image_tag 'title.png' %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <p class="navbar-text navbar-right">
        <%= current_admin.name %> 様
        <%= link_to "ログアウト", admin_signout_path, class:"navbar-link" %>
      </p>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/admin/_sidebar.erb
<div class="col-md-3">
  <div class="list-group">
    <a href="<%= admin_admins_url %>" class="list-group-item">管理者</a>
    <a href="<%= admin_companies_url %>" class="list-group-item">企業</a>
    <a href="<%= admin_staffs_url %>" class="list-group-item">スタッフ</a>
    <a href="<%= admin_markers_url %>" class="list-group-item">マーカー</a>
    <a href="<%= admin_characters_url %>" class="list-group-item">キャラクター</a>
    <a href="<%= admin_advertisings_url %>" class="list-group-item">広告</a>
    <a href="<%= admin_apps_url %>" class="list-group-item">アプリ</a>
  </div>
</div>

app/views/admin/admins/index.html.erb
<% content_for :content do %>
  <div class="container-fluid" align="right" style="margin-bottom: 20px;">
    <%= link_to '新規追加', new_admin_admin_path, class:"btn btn-primary" %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>名前</th>
        <th>メールアドレス</th>
      </tr>
    </thead>
    <tbody>
      <% @admins.each do |admin| %>
        <tr>
          <td><%= admin.id %></td>
          <td><%= admin.name %></td>
          <td><%= admin.email %></td>
          <td align='right'>
            <%= link_to '詳細', [:admin, admin], class:"btn btn-default" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<%= render :template => 'admin/frame' %>
<%
=begin
%>
<p id="notice"><%= notice %></p>

<h1>Listing Admins</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th>Password confirmation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.email %></td>
        <td><%= admin.password %></td>
        <td><%= admin.password_confirmation %></td>
        <td><%= link_to 'Show', [:admin, admin] %></td>
        <td><%= link_to 'Edit', edit_admin_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', [:admin, admin], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_admin_path %>
<%
=end
%>

app/views/admin/admins/new.html.erb
<% content_for :content do %>
  <% if @admin.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for([:admin, @admin]) do |f| %>
    <table class="table">
      <thead>
        <tr>
          <th>項目</th>
          <th>内容</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>名前</th>
          <td><%= f.text_field :name, class:"form-control", placeholder:"Name" %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= f.text_field :email, class:"form-control", placeholder:"Email" %></td>
        </tr>
        <tr>
          <th>パスワード</th>
          <td><%= f.password_field :password, class:"form-control", placeholder:"Password" %></td>
        </tr>
        <tr>
          <th>パスワード（確認）</th>
          <td><%= f.password_field :password_confirmation, class:"form-control", placeholder:"Confirm Password" %></td>
        </tr>
      </tbody>
    </table>
    <%= f.submit "作成", class:"btn btn-primary" %>
  <% end %>
<% end %>
<%= render :template => 'admin/frame' %>
<%
=begin
%>
<h1>New Admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_admins_path %>
<%
=end
%>

app/views/admin/admins/show.html.erb
<% content_for :content do %>
  <table class="table">
    <thead>
      <tr>
        <th>項目</th>
        <th>内容</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th>ID</th>
        <td><%= @admin.id %></td>
      </tr>
      <tr>
        <th>名前</th>
        <td><%= @admin.name %></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= @admin.email %></td>
      </tr>
    </tbody>
  </table>
  <%= button_to '削除', [:admin, @admin], method: :delete, data: { confirm: '本当に削除しますか？' }, class:"btn btn-danger" %>

<% end %>
<%= render :template => 'admin/frame' %>
<%
=begin
%>
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @admin.password %>
</p>

<p>
  <strong>Password confirmation:</strong>
  <%= @admin.password_confirmation %>
</p>

<%= link_to 'Edit', edit_admin_admin_path(@admin) %> |
<%= link_to 'Back', admin_admins_path %>

<%
=end
%>

app/views/admin/apps/edit.html.erb
<% content_for :content do %>
  <% if @app.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <ul>
      <% @app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for([:admin, @app]) do |f| %>
    <table class="table">
      <thead>
        <tr>
          <th>項目</th>
          <th>内容</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>ID</th>
          <td><%= @app.id %></td>
        </tr>
        <tr>
          <th>アプリ名</th>
          <td><%= f.text_field :name, class:"form-control", placeholder:"Name" %></td>
        </tr>
        <tr>
          <th>Android</th>
          <td><%= f.text_field :android_version, class:"form-control", placeholder:"1.0" %></td>
        </tr>
        <tr>
          <th>iOS</th>
          <td><%= f.text_field :ios_version, class:"form-control", placeholder:"1.0" %></td>
        </tr>
        <tr>
          <th>補足</th>
          <td>
            <%= f.text_area :memo, class:"form-control" %>
          </td>
        </tr>
      </tbody>
    </table>
    <%= f.submit "更新", class:"btn btn-default" %>
    <%= link_to '削除', [:admin, @app], method: :delete, data: { confirm: '本当に削除しますか？' }, class:"btn btn-danger" %>
  <% end %>
<% end %>
<%= render :template => 'admin/frame' %>

<%
=begin
%>
<h1>Editing App</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @app] %> |
<%= link_to 'Back', admin_apps_path %>

<%
=end
%>

app/views/admin/apps/index.html.erb
<% content_for :content do %>
  <div class="container-fluid" align="right" style="margin-bottom: 20px;">
    <%= link_to '新規追加', new_admin_app_path, class:"btn btn-primary" %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>アプリ名</th>
        <th>Android</th>
        <th>iOS</th>
        <th>補足</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @apps.each do |app| %>
        <tr>
          <td><%= app.id %></td>
          <td><%= app.name %></td>
          <td><%= app.android_version %></td>
          <td><%= app.ios_version %></td>
          <td><%= app.memo %></td>
          <td align='right'>
            <%= link_to '編集', edit_admin_app_path(app), class:"btn btn-default" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>
<%= render :template => 'admin/frame' %>
<%
=begin
%>


<p id="notice"><%= notice %></p>

<h1>Listing Apps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apps.each do |app| %>
      <tr>
        <td><%= app.name %></td>
        <td><%= link_to 'Show', [:admin, app] %></td>
        <td><%= link_to 'Edit', edit_admin_app_path(app) %></td>
        <td><%= link_to 'Destroy', [:admin, app], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App', new_admin_app_path %>

<%
=end
%>

app/views/admin/apps/new.html.erb
<% content_for :content do %>
  <% if @app.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <ul>
      <% @app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for([:admin, @app]) do |f| %>
    <table class="table">
      <thead>
        <tr>
          <th>項目</th>
          <th>内容</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>アプリ名</th>
          <td><%= f.text_field :name, class:"form-control", placeholder:"Name" %></td>
        </tr>
        <tr>
          <th>Android</th>
          <td><%= f.text_field :android_version, class:"form-control", placeholder:"1.0" %></td>
        </tr>
        <tr>
          <th>iOS</th>
          <td><%= f.text_field :ios_version, class:"form-control", placeholder:"1.0" %></td>
        </tr>
        <tr>
          <th>補足</th>
          <td>
            <%= f.text_area :memo, class:"form-control" %>
          </td>
        </tr>
      </tbody>
    </table>
    <%= f.submit "作成", class:"btn btn-default" %>
  <% end %>
<% end %>
<%= render :template => 'admin/frame' %>

<%
=begin
%>
<h1>New App</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_apps_path %>

<%
=end
%>

app/views/admin/frame.erb
<%= render 'admin/header' %>
<div class="container content">
  <div class="row">
    <%= render 'admin/sidebar' %>
    <div class="col-md-9">
      <% if flash[:notice] %>
        <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= flash[:notice] %>
        </div>
      <% end %>

      <%= yield :content %>
    </div>
  </div>
</div>