config/routes.rb
Rails.application.routes.draw do
  root to: 'company/welcome#index'

  namespace :admin do
    resources :admins, :except => [:edit]
    resources :markers, :except => [:show]
    resources :characters, :except => [:show]
    resources :companies, :except => [:show]
    resources :staffs, :except => [:show]
    resources :apps, :except => [:show]
    resources :advertisings, :except => [:show]
    get '/' => 'welcome#index'
    get '/signin' => 'sessions#signin'
    post '/signin' => 'sessions#create'
    get '/signout' => 'sessions#signout'
  end

  namespace :company do
    resources :staffs do
      collection do
        get :sign_in
        post 'session_create'
        delete :sign_out
      end
    end
    resources :markers, except: [:show], shallow: true do
      resources :advertisings
    end
    get '/' => 'welcome#index'
  end

  namespace :api, { format: 'json' } do
    namespace :v1 do
      post '/signup' => 'users#signup'
      get '/apps/:id/resources' => 'apps#resources'
      get '/apps/:id/relations' => 'apps#relations'
      post '/apps/:id/impressions' => 'apps#impressions'
      post '/apps/:id/reaches' => 'apps#reaches'
    end
  end

end

app/models/advertising.rb
class Advertising < ActiveRecord::Base
  belongs_to :marker
  has_many :impressions, :dependent => :destroy
  has_many :reaches, :dependent => :destroy

  mount_uploader :image, AdvertisingImageUploader


  validates :link, presence: true
  validates :image, presence: true
  validates :marker_id, presence: true

  scope :with_marker, -> (marker_id) { where(marker: marker_id) }
  scope :with_company, -> (company_id) { joins(marker: :company).merge(Company.where(id: company_id)) }

  def impressions_count
    impressions.count
  end

  def reaches_count
    reaches.count
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :apps_companies, :dependent => :destroy
  has_many :apps, :through => :apps_companies
  has_many :markers, :dependent => :destroy
  has_many :staffs, :dependent => :destroy
  belongs_to :character

  accepts_nested_attributes_for :apps_companies, :allow_destroy => true

  validates :name, presence: true
  validates :character_id, presence: true

  def impressions_count
    Impression.joins(advertising: {marker: :company}).merge(Company.where(id: id)).count
  end

  def reaches_count
    Reach.joins(advertising: {marker: :company}).merge(Company.where(id: id)).count
  end
end

app/controllers/admin/advertisings_controller.rb
class Admin::AdvertisingsController < ApplicationController
  before_action :authenticate_admin
  before_action :set_advertising, only: [:show, :edit, :update, :destroy]
  before_action :set_companies
  before_action :set_markers

  # GET /advertisings
  # GET /advertisings.json
  def index
    @advertisings = Advertising.all
  end

  # GET /advertisings/1
  # GET /advertisings/1.json
  def show
  end

  # GET /advertisings/new
  def new
    @advertising = Advertising.new
  end

  # GET /advertisings/1/edit
  def edit
  end

  # POST /advertisings
  # POST /advertisings.json
  def create
    @advertising = Advertising.new(advertising_params)

    respond_to do |format|
      if @advertising.save
        format.html { redirect_to admin_advertisings_url, notice: '作成しました' }
        #format.html { redirect_to [:admin, @advertising], notice: 'Advertising was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /advertisings/1
  # PATCH/PUT /advertisings/1.json
  def update
    respond_to do |format|
      if @advertising.update(advertising_params)
        format.html { redirect_to edit_admin_advertising_path(@advertising), notice: '更新しました' }
        #format.html { redirect_to [:admin, @advertising], notice: 'Advertising was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /advertisings/1
  # DELETE /advertisings/1.json
  def destroy
    @advertising.destroy
    respond_to do |format|
      format.html { redirect_to admin_advertisings_url, notice: '削除しました' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advertising
      @advertising = Advertising.find(params[:id])
    end

    def set_companies
      @companies = Company.all
    end

    def set_markers
      @markers = Marker.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advertising_params
      params.require(:advertising).permit(:marker_id, :image, :link, :enabled)
    end
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < ApplicationController
  before_action :authenticate_admin
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :set_apps
  before_action :set_character

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
    @company_app_ids = @company.apps.pluck(:id)
  end

  # GET /companies/1/edit
  def edit
    @company_app_ids = @company.apps.pluck(:id)
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    respond_to do |format|
      if @company.save
        @company.apps.build
        format.html { redirect_to admin_companies_url, notice: '作成しました' }
        #format.html { redirect_to [:admin, @company], notice: 'Company was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        @company.apps.build
        format.html { redirect_to edit_admin_company_path(@company), notice: '更新しました' }
        #format.html { redirect_to [:admin, @company], notice: 'Company was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to admin_companies_url, notice: '削除しました' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    def set_apps
      @apps = App.all
    end

    def set_character
      @characters = Character.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :enabled, :character_id, :max_marker, :max_advertise, app_ids:[])
    end
end

app/controllers/company/advertisings_controller.rb
class Company::AdvertisingsController < ApplicationController
  before_action :set_marker, only: [:index, :new, :create]
  before_action :set_advertising, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_staff

  # GET /advertisings
  # GET /advertisings.json
  def index
    @advertisings = Advertising.with_marker(@marker.id)
  end

  # GET /advertisings/1
  # GET /advertisings/1.json
  def show
    @reaches = Reach.with_advertising(params[:id])
    @impressions = Impression.with_advertising(params[:id])
  end

  # GET /advertisings/new
  def new
    @advertising = Advertising.new
    company = current_staff.company
    redirect_to company_marker_advertisings_path(@marker), alert: 'これ以上広告を追加することができません' if company.max_advertise <= Advertising.with_company(company.id).size
  end

  # GET /advertisings/1/edit
  def edit
  end

  # POST /advertisings
  # POST /advertisings.json
  def create
    @advertising = Advertising.new(advertising_params)
    @advertising.marker = @marker

    respond_to do |format|
      if @advertising.save
        format.html { redirect_to company_marker_advertisings_path(@marker), notice: '作成しました' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /advertisings/1
  # PATCH/PUT /advertisings/1.json
  def update
    respond_to do |format|
      if @advertising.update(advertising_params)
        format.html { redirect_to company_marker_advertisings_path(@advertising.marker), notice: '更新しました' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /advertisings/1
  # DELETE /advertisings/1.json
  def destroy
    marker = @advertising.marker
    @advertising.destroy
    respond_to do |format|
      format.html { redirect_to company_marker_advertisings_path(marker), notice: '削除しました' }
    end
  end

  private
    def set_marker
      @marker = Marker.find(params[:marker_id])
      unless current_staff.company == @marker.company
        redirect_to company_markers_path and return
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_advertising
      @advertising = Advertising.find(params[:id])
      unless current_staff.company == @advertising.marker.company
        redirect_to company_markers_path and return
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advertising_params
      params.require(:advertising).permit(:image, :link, :enabled)
    end
end

app/controllers/company/companies_controller.rb
class Company::CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_staff

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to [:admin, @company], notice: 'Company was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to [:admin, @company], notice: 'Company was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to admin_companies_url, notice: 'Company was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :disabled)
    end
end

app/controllers/company/markers_controller.rb
class Company::MarkersController < ApplicationController
  before_action :set_marker, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_staff

  # GET /markers
  # GET /markers.json
  def index
    @markers = Marker.with_company(current_staff.company.id)
  end

  # GET /markers/1
  # GET /markers/1.json
  def show
  end

  # GET /markers/new
  def new
    @marker = Marker.new
    company = current_staff.company
    redirect_to company_markers_path, alert: 'これ以上マーカーを追加することができません' if company.max_marker <= Marker.with_company(company.id).size
  end

  # GET /markers/1/edit
  def edit
  end

  # POST /markers
  # POST /markers.json
  def create
    @marker = Marker.new(marker_params)
    @marker.company = current_staff.company

    respond_to do |format|
      if @marker.save
        format.html { redirect_to company_markers_path, notice: '追加しました' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /markers/1
  # PATCH/PUT /markers/1.json
  def update
    respond_to do |format|
      if @marker.update(marker_params)
        format.html { redirect_to company_markers_path, notice: '更新しました' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /markers/1
  # DELETE /markers/1.json
  def destroy
    @marker.destroy
    respond_to do |format|
      format.html { redirect_to company_markers_url, notice: '削除しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marker
      @marker = Marker.find(params[:id])
      unless current_staff.company == @marker.company
        redirect_to company_markers_path and return
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marker_params
      params.require(:marker).permit(:name, :image)
    end
end

app/controllers/company/staffs_controller.rb
class Company::StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_staff, except: [:sign_in, :session_create]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.with_company(current_staff.company.id)
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to [:company, @staff], notice: '作成しました' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if staff_params[:password] == staff_params[:password_confirmation] && @staff.update(staff_params)
        format.html { redirect_to company_staffs_path, notice: '更新しました' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    session[:id] = nil
    respond_to do |format|
      format.html { redirect_to admin_staffs_url, notice: 'スタッフを削除しました' }
    end
  end

  def sign_in
    render layout: nil
  end

  def session_create
    login_params = params.require(:session).permit(:email, :password)
    email, password = login_params[:email], login_params[:password]
    staff = Staff.find_by_email(email)
    if staff && staff.authenticate(password)
      session[:id] = staff.id
      redirect_to company_staff_path(staff), notice: 'ログインしました'
    else
      render :sign_in
    end
  end

  def sign_out
    if current_staff
      session[:id] = nil
    end
    redirect_to company_staffs_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
      unless current_staff.company == @staff.company
        redirect_to company_staffs_path and return
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:company_id, :name, :email, :password, :password_confirmation)
    end
end

app/controllers/company/welcome_controller.rb
class Company::WelcomeController < ApplicationController
  before_action :authenticate_staff

  def index
  end
end

app/helpers/admin/advertisings_helper.rb
module Admin::AdvertisingsHelper
end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/views/company/advertisings/_form.html.erb
<% content_for :content do %>
  <%= form_for(shallow_args(:company, @marker, @advertising)) do |f| %>
    <table class="table">
      <thead>
      <tr>
        <th>項目</th>
        <th>内容</th>
      </tr>
      </thead>
      <tbody>
      <% if controller.action_name == 'edit' || controller.action_name == 'update' %>
          <tr>
            <th>ID</th>
            <td><%= @advertising.id %></td>
          </tr>
      <% end %>
      <tr>
        <th>リンク先</th>
        <td><%= f.text_field :link, class: 'form-control' %></td>
      </tr>
      <tr>
        <th>広告バナー</th>
        <td>
          <%= image_tag @advertising.image %>
          <%= f.file_field :image %>
        </td>
      </tr>
      <tr>
        <th>有効 / 無効</th>
        <td>
          <div class="btn-group" data-toggle="buttons">
            <label class="btn btn-default <%= if @advertising.enabled then 'active' end %>">
              <%= f.radio_button :enabled, 1, :checked => @advertising.enabled %> 有効
            </label>
            <label class="btn btn-default <%= unless @advertising.enabled then 'active' end %>">
              <%= f.radio_button :enabled, 0, :checked => !@advertising.enabled %>無効
            </label>
          </div>
        </td>
      </tr>
      </tbody>
    </table>
    <% if controller.action_name == 'new' || controller.action_name == 'create' %>
      <%= f.submit '作成', class: 'btn btn-default' %>
    <% else %>
      <%= f.submit '更新', class: 'btn btn-default' %>
      <%= link_to '削除', company_advertising_path(@advertising), method: :delete, class: 'btn btn-danger' %>
    <% end %>
  <% end %>
<% end %>
<%= render template: 'company/frame' %>

app/views/company/advertisings/edit.html.erb
<%= render 'form' %>

app/views/company/advertisings/index.html.erb
<% content_for :content do %>
  <% company = current_staff.company %>
  <div class="jumbotron">
    <h1><%= company.name %>様 管理画面</h1>
    <%= image_tag @marker.image.url %>
    <p>マーカー表示回数 : <%= @marker.reaches_count %> / マーカーに関する広告インプレッション数 : <%= @marker.impressions_count %></p>
  </div>
  <div class="container-fluid" align="right" style="margin-bottom: 20px;">
    <%= link_to '広告を新規追加', new_company_marker_advertising_path, class: 'btn btn-primary' %>
  </div>
  <table class="table">
    <thead>
    <tr>
      <th>#</th>
      <th>広告バナー</th>
      <th></th>
    </tr>
    </thead>
    <tbody>

    <% @advertisings.each do |advertising| %>
      <tr>
        <td><%= advertising.id %></td>
        <td>
          <%= image_tag advertising.image.url %>
        </td>
        <td align='right'>
          <%= link_to '詳細・広告表示履歴', company_advertising_path(advertising), class: 'btn btn-default' %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>
<%= render template: 'company/frame' %>

app/views/company/advertisings/new.html.erb
<%= render 'form' %>

app/views/company/advertisings/show.html.erb
<% content_for :content do %>
  <% company = current_staff.company %>
  <div class="jumbotron">
    <h1><%= company.name %>様 管理画面</h1>
    <%= image_tag @advertising.image.url %>
    <p>広告バナー表示回数 : <%= @advertising.reaches_count %> / 広告インプレッション数 : <%= @advertising.impressions_count %></p>
  </div>
  <div class="container-fluid" align="right" style="margin-bottom: 20px;">
    <%= link_to '広告を編集', edit_company_advertising_path(@advertising), class: 'btn btn-primary' %>
  </div>
  <div id="map" style="height: 400px; margin-top: 50px;"></div>
  <table class="table">
    <thead>
      <tr>
        <th>表示された日時</th>
        <th>場所</th>
      </tr>
      <% @reaches.each do |reach| %>
        <tr>
          <td><%= reach.displayed_at.strftime("%Y年 %m月 %d日, %H:%M:%S") %></td>
          <td><a onclick="addPin(<%= reach.latitude %>,<%= reach.longitude %>)">地図で場所を確認</a></td>
        </tr>
      <% end %>
    </thead>
    <tbody>
    </tbody>
  </table>
  <table class="table">
    <thead>
      <tr>
        <th>クリックされた日時</th>
        <th>場所</th>
      </tr>
      <% @impressions.each do |impression| %>
        <tr>
          <td><%= impression.displayed_at.strftime("%Y年 %m月 %d日, %H:%M:%S") %></td>
          <td><a onclick="addPin(<%= impression.latitude %>,<%= impression.longitude %>)">地図で場所を確認</a></td>
        </tr>
      <% end %>
    </thead>
    <tbody>
    </tbody>
  </table>

  <script type="text/javascript">
    var map;
    var data = [
      <% @reaches.each do |reach| %>
        {
          lat: <%= reach.latitude %>,
          lng: <%= reach.longitude %>,
          label: "<%= reach.displayed_at.strftime("%Y年 %m月 %d日, %H:%M:%S") %>"
        },
      <% end %>
    ]
    function initMap() {
      map = new google.maps.Map(document.getElementById('map'), {
        center: {lat: 33.5901528, lng: 130.3678963},
        zoom:   15
      });
      bounds = new google.maps.LatLngBounds();
      for (var i = 0; i < data.length; i++) {
        var latLng = new google.maps.LatLng(data[i].lat,data[i].lng);
        var marker = new google.maps.Marker({
          position: latLng,
          label: i + 1 + '',
          map: map
        });
        var infoWindow = new google.maps.InfoWindow({
          content: data[i].label
        });
        google.maps.event.addListener(marker, "click", function(event) {
          infoWindow.open(map, marker);
        });
        bounds.extend(latLng);
      }
      if(data.length > 0) {
        map.fitBounds(bounds);
      }
      addPin = function(latitude, longitude) {
        var latLng = new google.maps.LatLng(latitude,longitude);
        if (window.currentMarker !== undefined) {
          window.currentMarker.setMap(null);
        }
        window.currentMarker = new google.maps.Marker({
          position: latLng,
          map: map,
          color: 'green'
        });
        map.setCenter(latLng);
      }
    }
  </script>
  <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB2jwOz7ii2P1NsTdOtQX9d9zdwnsm9MdU&callback=initMap">
  </script>
<% end %>
<%= render template: 'company/frame' %>