config/routes.rb
Rails.application.routes.draw do
  root to: 'company/welcome#index'

  namespace :admin do
    resources :admins, :except => [:edit]
    resources :markers, :except => [:show]
    resources :characters, :except => [:show]
    resources :companies, :except => [:show]
    resources :staffs, :except => [:show]
    resources :apps, :except => [:show]
    resources :advertisings, :except => [:show]
    get '/' => 'welcome#index'
    get '/signin' => 'sessions#signin'
    post '/signin' => 'sessions#create'
    get '/signout' => 'sessions#signout'
  end

  namespace :company do
    resources :staffs do
      collection do
        get :sign_in
        post 'session_create'
        delete :sign_out
      end
    end
    resources :markers, except: [:show], shallow: true do
      resources :advertisings
    end
    get '/' => 'welcome#index'
  end

  namespace :api, { format: 'json' } do
    namespace :v1 do
      post '/signup' => 'users#signup'
      get '/apps/:id/resources' => 'apps#resources'
      get '/apps/:id/relations' => 'apps#relations'
      post '/apps/:id/impressions' => 'apps#impressions'
      post '/apps/:id/reaches' => 'apps#reaches'
    end
  end

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :apps_companies, :dependent => :destroy
  has_many :apps, :through => :apps_companies
  has_many :markers, :dependent => :destroy
  has_many :staffs, :dependent => :destroy
  belongs_to :character

  accepts_nested_attributes_for :apps_companies, :allow_destroy => true

  validates :name, presence: true
  validates :character_id, presence: true

  def impressions_count
    Impression.joins(advertising: {marker: :company}).merge(Company.where(id: id)).count
  end

  def reaches_count
    Reach.joins(advertising: {marker: :company}).merge(Company.where(id: id)).count
  end
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  belongs_to :company

  validates :name, presence: true
  validates :company_id, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  has_secure_password

  scope :with_company, -> (company_id) { where(company: company_id) }
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < ApplicationController
  before_action :authenticate_admin
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :set_apps
  before_action :set_character

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
    @company_app_ids = @company.apps.pluck(:id)
  end

  # GET /companies/1/edit
  def edit
    @company_app_ids = @company.apps.pluck(:id)
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    respond_to do |format|
      if @company.save
        @company.apps.build
        format.html { redirect_to admin_companies_url, notice: '作成しました' }
        #format.html { redirect_to [:admin, @company], notice: 'Company was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        @company.apps.build
        format.html { redirect_to edit_admin_company_path(@company), notice: '更新しました' }
        #format.html { redirect_to [:admin, @company], notice: 'Company was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to admin_companies_url, notice: '削除しました' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    def set_apps
      @apps = App.all
    end

    def set_character
      @characters = Character.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :enabled, :character_id, :max_marker, :max_advertise, app_ids:[])
    end
end

app/controllers/admin/staffs_controller.rb
class Admin::StaffsController < ApplicationController
  before_action :authenticate_admin
  before_action :set_staff, only: [:show, :edit, :update, :destroy]
  before_action :set_company

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to admin_staffs_url, notice: '作成しました' }
        #format.html { redirect_to [:admin, @staff], notice: 'Staff was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to edit_admin_staff_path(@staff), notice: '更新しました' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to admin_staffs_url, notice: '削除しました' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end
    def set_company
      @companies = Company.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:name, :company_id, :email, :password, :password_confirmation)
    end
end

app/controllers/company/advertisings_controller.rb
class Company::AdvertisingsController < ApplicationController
  before_action :set_marker, only: [:index, :new, :create]
  before_action :set_advertising, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_staff

  # GET /advertisings
  # GET /advertisings.json
  def index
    @advertisings = Advertising.with_marker(@marker.id)
  end

  # GET /advertisings/1
  # GET /advertisings/1.json
  def show
    @reaches = Reach.with_advertising(params[:id])
    @impressions = Impression.with_advertising(params[:id])
  end

  # GET /advertisings/new
  def new
    @advertising = Advertising.new
    company = current_staff.company
    redirect_to company_marker_advertisings_path(@marker), alert: 'これ以上広告を追加することができません' if company.max_advertise <= Advertising.with_company(company.id).size
  end

  # GET /advertisings/1/edit
  def edit
  end

  # POST /advertisings
  # POST /advertisings.json
  def create
    @advertising = Advertising.new(advertising_params)
    @advertising.marker = @marker

    respond_to do |format|
      if @advertising.save
        format.html { redirect_to company_marker_advertisings_path(@marker), notice: '作成しました' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /advertisings/1
  # PATCH/PUT /advertisings/1.json
  def update
    respond_to do |format|
      if @advertising.update(advertising_params)
        format.html { redirect_to company_marker_advertisings_path(@advertising.marker), notice: '更新しました' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /advertisings/1
  # DELETE /advertisings/1.json
  def destroy
    marker = @advertising.marker
    @advertising.destroy
    respond_to do |format|
      format.html { redirect_to company_marker_advertisings_path(marker), notice: '削除しました' }
    end
  end

  private
    def set_marker
      @marker = Marker.find(params[:marker_id])
      unless current_staff.company == @marker.company
        redirect_to company_markers_path and return
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_advertising
      @advertising = Advertising.find(params[:id])
      unless current_staff.company == @advertising.marker.company
        redirect_to company_markers_path and return
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advertising_params
      params.require(:advertising).permit(:image, :link, :enabled)
    end
end

app/controllers/company/companies_controller.rb
class Company::CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_staff

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to [:admin, @company], notice: 'Company was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to [:admin, @company], notice: 'Company was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to admin_companies_url, notice: 'Company was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :disabled)
    end
end

app/controllers/company/markers_controller.rb
class Company::MarkersController < ApplicationController
  before_action :set_marker, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_staff

  # GET /markers
  # GET /markers.json
  def index
    @markers = Marker.with_company(current_staff.company.id)
  end

  # GET /markers/1
  # GET /markers/1.json
  def show
  end

  # GET /markers/new
  def new
    @marker = Marker.new
    company = current_staff.company
    redirect_to company_markers_path, alert: 'これ以上マーカーを追加することができません' if company.max_marker <= Marker.with_company(company.id).size
  end

  # GET /markers/1/edit
  def edit
  end

  # POST /markers
  # POST /markers.json
  def create
    @marker = Marker.new(marker_params)
    @marker.company = current_staff.company

    respond_to do |format|
      if @marker.save
        format.html { redirect_to company_markers_path, notice: '追加しました' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /markers/1
  # PATCH/PUT /markers/1.json
  def update
    respond_to do |format|
      if @marker.update(marker_params)
        format.html { redirect_to company_markers_path, notice: '更新しました' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /markers/1
  # DELETE /markers/1.json
  def destroy
    @marker.destroy
    respond_to do |format|
      format.html { redirect_to company_markers_url, notice: '削除しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marker
      @marker = Marker.find(params[:id])
      unless current_staff.company == @marker.company
        redirect_to company_markers_path and return
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marker_params
      params.require(:marker).permit(:name, :image)
    end
end

app/controllers/company/staffs_controller.rb
class Company::StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_staff, except: [:sign_in, :session_create]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.with_company(current_staff.company.id)
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to [:company, @staff], notice: '作成しました' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if staff_params[:password] == staff_params[:password_confirmation] && @staff.update(staff_params)
        format.html { redirect_to company_staffs_path, notice: '更新しました' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    session[:id] = nil
    respond_to do |format|
      format.html { redirect_to admin_staffs_url, notice: 'スタッフを削除しました' }
    end
  end

  def sign_in
    render layout: nil
  end

  def session_create
    login_params = params.require(:session).permit(:email, :password)
    email, password = login_params[:email], login_params[:password]
    staff = Staff.find_by_email(email)
    if staff && staff.authenticate(password)
      session[:id] = staff.id
      redirect_to company_staff_path(staff), notice: 'ログインしました'
    else
      render :sign_in
    end
  end

  def sign_out
    if current_staff
      session[:id] = nil
    end
    redirect_to company_staffs_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
      unless current_staff.company == @staff.company
        redirect_to company_staffs_path and return
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:company_id, :name, :email, :password, :password_confirmation)
    end
end

app/controllers/company/welcome_controller.rb
class Company::WelcomeController < ApplicationController
  before_action :authenticate_staff

  def index
  end
end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/helpers/admin/staffs_helper.rb
module Admin::StaffsHelper
end

app/views/company/staffs/_form.html.erb
<% content_for :content do %>
  <%= form_for([:company, @staff]) do |f| %>
    <table class="table">
      <thead>
      <tr>
        <th>項目</th>
        <th>内容</th>
      </tr>
      </thead>
      <tbody>
      <% if controller.action_name == 'edit' || controller.action_name == 'update' %>
        <tr>
          <th>ID</th>
          <td><%= @staff.id %></td>
        </tr>
      <% end %>
      <tr>
        <th>名前</th>
        <% if controller.action_name == 'new' || controller.action_name == 'create' %>
          <td><%= f.text_field :name, class: 'form-control' %></td>
        <% else %>
          <td><%= @staff.name %></td>
        <% end %>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= f.email_field :email, class: 'form-control', placeholder: 'Email' %></td>
      </tr>
      <tr>
        <th>パスワード</th>
        <td><%= f.password_field :password, class: 'form-control', placeholder: 'Password' %></td>
      </tr>
      <tr>
        <th>パスワード(確認用)</th>
        <td><%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Password' %></td>
      </tr>
      </tbody>
    </table>
        <% if controller.action_name == 'new' || controller.action_name == 'create' %>
          <%= f.submit '作成', class: 'btn btn-default' %>
        <% else %>
          <%= f.submit '更新', class: 'btn btn-default' %>
          <%= link_to '削除', company_staff_path(@staff), method: :delete, class: 'btn btn-danger' %>
        <% end %>
  <% end %>
<% end %>
<%= render template: 'company/frame' %>

app/views/company/staffs/index.html.erb
<% content_for :content do %>
  <div class="container-fluid" align="right">
    <%= link_to '新規追加', new_company_staff_path, class: 'btn btn-primary' %>
  </div>
  <table class="table">
    <thead>
    <tr>
      <th>#</th>
      <th>名前</th>
      <th>メールアドレス</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
      <% @staffs.each do |staff| %>
        <tr>
          <td><%= staff.id %></td>
          <td><%= staff.name %></td>
          <td><%= staff.email %></td>
          <td align="right">
            <%= link_to '編集', edit_company_staff_path(staff), {class: 'btn btn-default'} %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<%= render template: 'company/frame' %>

app/views/company/staffs/show.html.erb
<% content_for :content do %>
  <table class="table">
    <thead>
    <tr>
      <th>項目</th>
      <th>内容</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <th>ID</th>
      <td><%= @staff.id %></td>
    </tr>
    <tr>
      <th>名前</th>
      <td><%= @staff.name %></td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td><%= @staff.email %></td>
    </tr>
    </tbody>
  </table>
<% end %>
<%= render template: 'company/frame' %>

app/views/company/staffs/sign_in.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kamiproar</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="login">
    <% if notice %>
      <div class="container">
        <div class="alert alert-success" role="alert"><%= notice %></div>
      </div>
    <% end %>
    <%= form_tag session_create_company_staffs_path, class: 'form-signin' do %>
      <h2 class="form-signin-heading">sagascope ログイン</h2>
      <label class="sr-only">Login ID</label>
      <input type="text" class="form-control" placeholder="Email" required autofocus name="session[email]">
      <label class="sr-only">Password</label>
      <input type="password" class="form-control" placeholder="Password" required name="session[password]">
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    <% end %>
  </body>
</html>