config/routes.rb
Rails.application.routes.draw do
  root to: 'company/welcome#index'

  namespace :admin do
    resources :admins, :except => [:edit]
    resources :markers, :except => [:show]
    resources :characters, :except => [:show]
    resources :companies, :except => [:show]
    resources :staffs, :except => [:show]
    resources :apps, :except => [:show]
    resources :advertisings, :except => [:show]
    get '/' => 'welcome#index'
    get '/signin' => 'sessions#signin'
    post '/signin' => 'sessions#create'
    get '/signout' => 'sessions#signout'
  end

  namespace :company do
    resources :staffs do
      collection do
        get :sign_in
        post 'session_create'
        delete :sign_out
      end
    end
    resources :markers, except: [:show], shallow: true do
      resources :advertisings
    end
    get '/' => 'welcome#index'
  end

  namespace :api, { format: 'json' } do
    namespace :v1 do
      post '/signup' => 'users#signup'
      get '/apps/:id/resources' => 'apps#resources'
      get '/apps/:id/relations' => 'apps#relations'
      post '/apps/:id/impressions' => 'apps#impressions'
      post '/apps/:id/reaches' => 'apps#reaches'
    end
  end

end

app/models/marker.rb
class Marker < ActiveRecord::Base
  belongs_to :company
  has_many :advertisings, :dependent => :destroy

  mount_uploader :image, MarkerImageUploader
  before_destroy :validate_updated_at
  after_destroy :delete_from_vuforia


  validates :name, presence: true
  validates :company_id, presence: true
  validates :image, presence: true

  validate :validate_updated_at, on: :update

  scope :with_company, -> (company_id) { where(company: company_id) }

  def impressions_count
    Impression.joins(advertising: :marker).merge(Marker.where(id: id)).count
  end

  def reaches_count
    Reach.joins(advertising: :marker).merge(Marker.where(id: id)).count
  end

  def delete_from_vuforia
    Vuforia.delete target_id
  end

private
  def validate_updated_at
    if updated_at + 120 > Time.now
      errors.add(" ", "連続して変更することはできません。約120秒待って再度実行してください")
      return false
    end
  end
end

app/controllers/admin/markers_controller.rb
class Admin::MarkersController < ApplicationController
  before_action :authenticate_admin
  before_action :set_marker, only: [:show, :edit, :update, :destroy]
  before_action :set_companies

  # GET /markers
  # GET /markers.json
  def index
    @markers = Marker.all
  end

  # GET /markers/1
  # GET /markers/1.json
  def show
  end

  # GET /markers/new
  def new
    @marker = Marker.new
  end

  # GET /markers/1/edit
  def edit
  end

  # POST /markers
  # POST /markers.json
  def create
    @marker = Marker.new(marker_params)

    respond_to do |format|
      if @marker.save
        if Vuforia.upload @marker
          format.html { redirect_to admin_markers_url, notice: '作成しました' }
        else
          format.html { render :edit }
        end
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /markers/1
  # PATCH/PUT /markers/1.json
  def update
    respond_to do |format|
      if @marker.update(marker_params)
        if Vuforia.upload @marker
          format.html { redirect_to edit_admin_marker_path(@marker), notice: '更新しました' }
          #format.html { redirect_to [:admin, @marker], notice: 'Marker was successfully updated.' }
        else
          format.html { render :edit }
        end
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /markers/1
  # DELETE /markers/1.json
  def destroy
    respond_to do |format|
      if @marker.destroy
        format.html { redirect_to admin_markers_url, notice: '削除しました' }
      else
        format.html { render :edit }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marker
      @marker = Marker.find(params[:id])
    end
    def set_companies
      @companies = Company.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marker_params
      params.require(:marker).permit(:company_id, :target_id, :enabled, :image, :image_cache, :name)
    end
end

app/controllers/company/markers_controller.rb
class Company::MarkersController < ApplicationController
  before_action :set_marker, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_staff

  # GET /markers
  # GET /markers.json
  def index
    @markers = Marker.with_company(current_staff.company.id)
  end

  # GET /markers/1
  # GET /markers/1.json
  def show
  end

  # GET /markers/new
  def new
    @marker = Marker.new
    company = current_staff.company
    redirect_to company_markers_path, alert: 'これ以上マーカーを追加することができません' if company.max_marker <= Marker.with_company(company.id).size
  end

  # GET /markers/1/edit
  def edit
  end

  # POST /markers
  # POST /markers.json
  def create
    @marker = Marker.new(marker_params)
    @marker.company = current_staff.company

    respond_to do |format|
      if @marker.save
        format.html { redirect_to company_markers_path, notice: '追加しました' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /markers/1
  # PATCH/PUT /markers/1.json
  def update
    respond_to do |format|
      if @marker.update(marker_params)
        format.html { redirect_to company_markers_path, notice: '更新しました' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /markers/1
  # DELETE /markers/1.json
  def destroy
    @marker.destroy
    respond_to do |format|
      format.html { redirect_to company_markers_url, notice: '削除しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marker
      @marker = Marker.find(params[:id])
      unless current_staff.company == @marker.company
        redirect_to company_markers_path and return
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marker_params
      params.require(:marker).permit(:name, :image)
    end
end

app/helpers/admin/markers_helper.rb
module Admin::MarkersHelper
end

app/views/admin/markers/edit.html.erb
<% content_for :content do %>
  <% if @marker.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <ul>
      <% @marker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for([:admin, @marker]) do |f| %>
    <table class="table">
      <thead>
        <tr>
          <th>項目</th>
          <th>内容</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>ID</th>
          <td><%= @marker.id %></td>
        </tr>
        <tr>
          <th>名前</th>
          <td><%= f.text_field :name, class:"form-control", placeholder:"Name" %></td>
        </tr>
        <tr>
          <th>企業</th>
          <td>
            <%= f.collection_select :company_id, @companies, :id,  :name, {}, class:"form-control" %>
          </td>
        </tr>
        <tr>
          <th>有効/無効</th>
          <td>
            <div class="btn-group" data-toggle="buttons">
            	<label class="btn btn-default <%= if @marker.enabled then 'active' end %>">
                <%= f.radio_button :enabled, 1, :checked => @marker.enabled %> 有効
            	</label>
            	<label class="btn btn-default <%= unless @marker.enabled then 'active' end %>">
            		<%= f.radio_button :enabled, 0, :checked => !@marker.enabled %>無効
            	</label>
            </div>
          </td>
        </tr>
        <tr>
          <th>マーカー画像</th>
          <td>
            <%= image_tag @marker.image.url %><br>
            <%= f.file_field :image %>
            <%= f.hidden_field :image_cache %>
          </td>
        </tr>
      </tbody>
    </table>
    <%= f.submit "更新", class:"btn btn-default" %>
    <%= link_to '削除', [:admin, @marker], method: :delete, data: { confirm: '本当に削除しますか？' }, class:"btn btn-danger" %>
  <% end %>
<% end %>
<%= render :template => 'admin/frame' %>

<%
=begin
%>
<h1>Editing Marker</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @marker] %> |
<%= link_to 'Back', admin_markers_path %>

<%
=end
%>

app/views/admin/markers/index.html.erb
<% content_for :content do %>
  <div class="container-fluid" align="right" style="margin-bottom: 20px;">
    <%= link_to '新規追加', new_admin_marker_path, class:"btn btn-primary" %>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>名前</th>
        <th>企業名</th>
        <th>有効 / 無効</th>
        <th>画像</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @markers.each do |marker| %>
        <tr>
          <td><%= marker.id %></td>
          <td><%= marker.name %></td>
          <td><%= marker.company.name %></td>
          <td><%= if marker.enabled then "有効" else "無効" end %></td>
          <td><%= image_tag marker.image.url(:thumbnail) %></td>
          <td align='right'>
            <%= link_to '編集', edit_admin_marker_path(marker), class:"btn btn-default" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<%= render :template => 'admin/frame' %>
<%
=begin
%>

<p id="notice"><%= notice %></p>

<h1>Listing Markers</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @markers.each do |marker| %>
      <tr>
        <td><%= marker.company_id %></td>
        <td><%= marker.image_url %></td>
        <td><%= link_to 'Show', [:admin, marker] %></td>
        <td><%= link_to 'Edit', edit_admin_marker_path(marker) %></td>
        <td><%= link_to 'Destroy', [:admin, marker], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Marker', new_admin_marker_path %>

<%
=end
%>

app/views/admin/markers/new.html.erb
<% content_for :content do %>
  <% if @marker.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <ul>
      <% @marker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for([:admin, @marker]) do |f| %>
    <table class="table">
      <thead>
        <tr>
          <th>項目</th>
          <th>内容</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>名前</th>
          <td><%= f.text_field :name, class:"form-control", placeholder:"Name" %></td>
        </tr>
        <tr>
          <th>企業</th>
          <td>
            <%= f.collection_select :company_id, @companies, :id,  :name, {}, class:"form-control" %>
          </td>
        </tr>
        <tr>
          <th>有効/無効</th>
          <td>
            <div class="btn-group" data-toggle="buttons">
            	<label class="btn btn-default <%= if @marker.enabled then 'active' end %>">
                <%= f.radio_button :enabled, 1, :checked => @marker.enabled %> 有効
            	</label>
            	<label class="btn btn-default <%= unless @marker.enabled then 'active' end %>">
            		<%= f.radio_button :enabled, 0, :checked => !@marker.enabled %>無効
            	</label>
            </div>
          </td>
        </tr>
        <tr>
          <th>マーカー画像</th>
          <td>
            <%= image_tag @marker.image.url %><br>
            <%= f.file_field :image %>
            <%= f.hidden_field :image_cache %>
          </td>
        </tr>
      </tbody>
    </table>
    <%= f.submit "作成", class:"btn btn-primary" %>
  <% end %>
<% end %>
<%= render :template => 'admin/frame' %>

<%
=begin
%>

<h1>New Marker</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_markers_path %>
<%
=end
%>